stages:
  - build
  # - Test
  - deploy

build:
  stage: build
  image: registry.gitlab.com/mishamilovidov/mishamilovidov
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build/*
      - node_modules/*
      - public/*
      - src/*
      - .firebaserc
      - firebase.json
      - package.json
      - package-lock.json

deploy-prod:
  stage: deploy
  image: registry.gitlab.com/mishamilovidov/mishamilovidov
  only:
    - master
  when: on_success
  environment:
    name: production
    url: https://mishamilovidov.com
  dependencies:
    - build
  script:
    - npm install firebase-tools
    - ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
