export const FETCH_BLOG_POST_SUCCESS = 'FETCH_BLOG_POST_SUCCESS';
export const FETCH_BLOG_POST_LOADING = 'FETCH_BLOG_POST_LOADING';
export const FETCH_BLOG_POST_FAILURE = 'FETCH_BLOG_POST_FAILURE';
export const FETCH_BLOG_POSTS_LOADING = 'FETCH_BLOG_POSTS_LOADING';
export const FETCH_BLOG_POSTS_SUCCESS = 'FETCH_BLOG_POSTS_SUCCESS';
export const FETCH_BLOG_POSTS_FAILURE = 'FETCH_BLOG_POSTS_FAILURE';